core:test coverage

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -43,28 +43,72 @@ jobs:
         run: make compile
 
       - name: 🧪 Unit test
-        run: go test -race -tags=unit ./... -coverprofile=./ubuntu-latest-profile.out -covermode=atomic -coverpkg=./...
+        run: go test -race -tags=unit -coverprofile=ubuntu-latest-profile -covermode=atomic -coverpkg=./... ./...
+
+      - name: ⬆️ upload coverage breakdown artifact (main.breakdown)
+        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 #v4.6.0
+        if: github.ref_name == 'main'
+        with:
+          name: ubuntu-latest-profile
+          path: ubuntu-latest-profile
+          if-no-files-found: error
+
+      - name: 🚀 Binary starts
+        run: go run ./cmd/monaco
+
+  check-coverage:
+    needs: build_test
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+
+      - name: download ubuntu-latest-profile
+        uses: actions/download-artifact@v4
+        with:
+          name: ubuntu-latest-profile
+
+      - name: download artifact (main.breakdown)
+        id: download-main-breakdown
+        uses: dawidd6/action-download-artifact@v8
+        with:
+          branch: main
+          workflow_conclusion: success
+          name: main.breakdown
+          if_no_artifact_found: fail
 
       - name: check test coverage
+        id: coverage
         uses: vladopajic/go-test-coverage@v2
-        continue-on-error: true
+        continue-on-error: true # Should fail after coverage comment is posted
         with:
           config: ./.github/.testcoverage.yml
           profile: ubuntu-latest-profile
           breakdown-file-name: ${{ github.ref_name == 'main' && 'main.breakdown' || '' }}
           diff-base-breakdown-file-name: ${{ steps.download-main-breakdown.outputs.found_artifact == 'true' && 'main.breakdown' || '' }}
 
+      - name: upload artifact (main.breakdown)
+        uses: actions/upload-artifact@v4
+        if: github.ref_name == 'main'
+        with:
+          name: main.breakdown
+          path: main.breakdown
+          if-no-files-found: error
+
+      # Post coverage report as comment
       - name: find pull request ID
         run: |
           PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-          "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref_name }}&state=open")
+            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref_name }}&state=open")
           PR_ID=$(echo "$PR_DATA" | jq -r '.[0].number')
 
           if [ "$PR_ID" != "null" ]; then
-          echo "pull_request_id=$PR_ID" >> $GITHUB_ENV
+            echo "pull_request_id=$PR_ID" >> $GITHUB_ENV
           else
-          echo "No open pull request found for this branch."
+            echo "No open pull request found for this branch."
           fi
+
       - name: find if coverage report is already present
         if: env.pull_request_id
         uses: peter-evans/find-comment@v3
@@ -73,6 +117,7 @@ jobs:
           issue-number: ${{ env.pull_request_id }}
           comment-author: 'github-actions[bot]'
           body-includes: 'go-test-coverage report:'
+
       - name: post coverage report
         if: env.pull_request_id
         uses: peter-evans/create-or-update-comment@v4
@@ -84,25 +129,10 @@ jobs:
           body: |
             go-test-coverage report:
             ```
-            ${{ fromJSON(steps.coverage.outputs.report) }} ```
+            ${{ fromJSON(steps.coverage.outputs.report) }}```
 
-      - name: ⬆️ upload coverage breakdown artifact (main.breakdown)
-        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 #v4.6.0
-        if: github.ref_name == 'main'
-        with:
-          name: main.breakdown
-          path: main.breakdown # as specified via `breakdown-file-name`
-          if-no-files-found: error
+      - name: "finally check coverage"
+        if: steps.coverage.outcome == 'failure'
+        shell: bash
+        run: echo "coverage check failed" && exit 1
 
-      - name: 🚀 Binary starts
-        run: go run ./cmd/monaco
-
-  upload_event:
-    name: "Upload Event File"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Upload
-        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 #v4.6.0
-        with:
-          name: event_file
-          path: ${{ github.event_path }}
